services:
  db: # имя сервиса. Оно может быть любым
    image: postgres:14-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    #    volumes:
    #      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
