services:
  db: # имя сервиса. Оно может быть любым
    image: postgres:16.1
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
