CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
--
--CREATE TABLE IF NOT EXISTS items (
--  item_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--  name VARCHAR NOT NULL,
--  description VARCHAR NOT NULL,
--  is_available BOOLEAN,
--  owner_id INT NOT NULL REFERENCES users (user_id),
--  request_id INT REFERENCES requests (request_id)
--);
--
--CREATE TABLE IF NOT EXISTS bookings (
--    booking_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--    start_date TIMESTAMP NOT NULL,
--    end_date TIMESTAMP NOT NULL,
--    status VARCHAR,
--    item_id INT REFERENCES items (item_id),
--    booker_id INT REFERENCES users (user_id)
--);
--
--CREATE TABLE IF NOT EXISTS requests (
--    request_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--    description VARCHAR,
--    requestor_id INT REFERENCES users (user_id)
--);
--
--CREATE TABLE IF NOT EXISTS comments (
--    comment_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--    text VARCHAR,
--    item_id INT REFERENCES items (item_id),
--    author_id INT REFERENCES users (user_id)
--);
